APLICACION_CULTIVO_HIDROPONICO/Controllers/PlantaController.cs
using CAPA_ENTIDADES_NEGOCIO.CLASES;
using CAPA_LOGICA_NEGOCIO.CLASES;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Security.Claims;
using WS_Altura_Planta;

namespace APLICACION_CULTIVO_HIDROPONICO.Controllers
{
    [Authorize]
    public class PlantaController : Controller
    {
        private UsuarioBE DatosUsuarioSesion()
        {
            var Identity = HttpContext.User.Identity as ClaimsIdentity;
            var DatosUsuarioJson = Identity.FindFirst(ClaimTypes.UserData).Value;
            return JsonConvert.DeserializeObject<UsuarioBE>(DatosUsuarioJson);
        }

        public IActionResult VerPlantas()
        {
            PlantaBL PlantaBL = new();
            List<PlantaBE> ListaPlantas = PlantaBL.ObtenerPlantas(DatosUsuarioSesion().Id_Usuario);

            VariableBL VariableBL = new();
            List<VariableBE> Variables = VariableBL.TraerVariables();

            AmbienteBL AmbienteBL = new();
            List<AmbienteBE> AmbienteBE = AmbienteBL.VerAmbiente();

            PlantaBE_VariablesBE_AmbienteBE PV = new()
            {
                Plantas = ListaPlantas,
                Variables = Variables,
                Ambiente = AmbienteBE
            };

            return View(PV);
        }

        public IActionResult VerPlanta(int IdPlanta)
        {
            PlantaBL PlantaBL = new();
            PlantaBE PlantaBE = PlantaBL.ObtenerPlanta(IdPlanta);

            UnidadMedidaPlantaBL UMPBL = new();
            List<UnidadMedidaPlantaBE> UMPBE = UMPBL.TraerUnidadesMedidasPlanta();

            UnidadTiempoPlantaBL UTPBL = new();
            List<UnidadTiempoPlantaBE> UTPBE = UTPBL.TraerUnidadesTiempoPlanta();

            TipoPlantaBL TPPBL = new();
            List<TipoPlantaBE> TPBE = TPPBL.TraerTiposPlantas();

            AmbienteBL AmbienteBL = new();
            List<AmbienteBE> AmbienteBE = AmbienteBL.VerAmbiente();

            PlantaBE_TipoPlantaBE_UnidadMedidaPlantaBE_UnidadTiempoPlantaBE_AmbienteBE PTMT = new()
            {
                Planta = PlantaBE,
                UnidadesM = UMPBE,
                UnidadesT = UTPBE,
                Tipos = TPBE,
                AmbienteBE = AmbienteBE,
                RolUsuarioEnSesion = DatosUsuarioSesion().Rol_Usuario
            };
            return View(PTMT);
        }

        public IActionResult CambiarNombrePlanta(string NombrePlanta, int IdPlanta)
        {
            PlantaBL PlantaBL = new();
            PlantaBL.CambiarNombrePlanta(NombrePlanta, IdPlanta);
            VerPlanta(IdPlanta);
            return View("VerPlanta");
        }

        public IActionResult CambiarDiametroTalloPlanta(double DiametroTalloPlanta, int IdPlanta, int UnidadMedidaPlanta)
        {
            PlantaBL PlantaBL = new();
            PlantaBL.CambiarDiametroTalloPlanta(DiametroTalloPlanta, IdPlanta);
            PlantaBL.CambiarUnidadMedidaPlanta(UnidadMedidaPlanta, IdPlanta);

            VerPlanta(IdPlanta);
            return View("VerPlanta");
        }

        public IActionResult CambiarTiempoCultivoPlanta(double TiempoCultivoPlanta, int IdPlanta, int UnidadTiempoPlanta)
        {
            PlantaBL PlantaBL = new();
            PlantaBL.CambiarTiempoCultivoPlanta(TiempoCultivoPlanta, IdPlanta);
            PlantaBL.CambiarUnidadTiempoPlanta(UnidadTiempoPlanta, IdPlanta);
            VerPlanta(IdPlanta);
            return View("VerPlanta");
        }

        public IActionResult CambiarCantidadHojasPlanta(int CantidadHojasPlanta, int IdPlanta)
        {
            PlantaBL PlantaBL = new();
            PlantaBL.CambiarCantidadHojasPlanta(CantidadHojasPlanta, IdPlanta);
            VerPlanta(IdPlanta);
            return View("VerPlanta");
        }

        public IActionResult CambiarTipoPlanta(int TipoPlanta, int IdPlanta)
        {
            PlantaBL PlantaBL = new();
            PlantaBL.CambiarTipoPlanta(TipoPlanta, IdPlanta);
            VerPlanta(IdPlanta);
            return View("VerPlanta");
        }

        public IActionResult EliminarPlanta(int IdPlanta)
        {
            PlantaBL PlantaBL = new();
            PlantaBL.EliminarPlanta(IdPlanta);
            VerPlantas();
            return View("VerPlantas");
        }

        public IActionResult RegistarPlanta()
        {
            TipoPlantaBL TipoPlantaBL = new();
            UnidadMedidaPlantaBL UnidadMedidaPlantaBL = new();
            UnidadTiempoPlantaBL UnidadTiempoPlantaBL = new();
            TipoPlantaBE_UnidadMedidaPlantaBE_UnidadTiempoPlantaBE TPUMUT = new()
            {
                UnidadMedidaPlantaBE = UnidadMedidaPlantaBL.TraerUnidadesMedidasPlanta(),
                UnidadTiempoPlantaBE = UnidadTiempoPlantaBL.TraerUnidadesTiempoPlanta(),
                TipoPlantaBE = TipoPlantaBL.TraerTiposPlantas()
            };
            return View(TPUMUT);
        }

        public IActionResult CrearPlanta(string NombrePlanta, double DiametroTallo, double TiempoCultivo, int CantidadHojas, int TipoPlanta, int UnidadMeida, int UnidadTiempo)
        {
            PlantaBL PlantaBL = new();
            PlantaBL.RegistrarPlanta(NombrePlanta, DiametroTallo, TiempoCultivo, CantidadHojas, DatosUsuarioSesion().Id_Usuario, TipoPlanta, UnidadMeida, UnidadTiempo);
            VerPlantas();
            return View("VerPlantas");
        }

        public IActionResult CapturarAlturaPlanta(int IdPlanta)
        {
            double AlturaPlanta = 0;
            try
            {
                CapturarAlturaClient ClienteALturaPlanta = new();
                AlturaPlanta = ClienteALturaPlanta.AlturaValorClienteAsync().Result.@return;
                Console.WriteLine(AlturaPlanta);
            }
            catch (Exception ex) { Console.WriteLine(ex.Message); }
            PlantaBL PlantaBL = new();
            PlantaBL.CambiarAlturaPlanta(IdPlanta, AlturaPlanta);
            VerPlanta(IdPlanta);
            return View("VerPlanta");
        }

        public IActionResult AgregarUnidadMedidaPlanta(string UnidadMedida, string SimboloUnidad, int IdPlanta)
        {
            UnidadMedidaPlantaBL UnidadMedidaPlantaBL = new();
            UnidadMedidaPlantaBL.AgregarUnidadMedidaPlanta(UnidadMedida, SimboloUnidad);
            VerPlanta(IdPlanta);
            return View("VerPlanta");
        }

        public IActionResult AgregarUnidadTiempoPlanta(string UnidadTiempo, int IdPlanta)
        {
            UnidadTiempoPlantaBL UnidadTiempoPlantaBL = new();
            UnidadTiempoPlantaBL.AgregarUnidadTiempoPlanta(UnidadTiempo);
            VerPlanta(IdPlanta);
            return View("VerPlanta");
        }
    }
}

APLICACION_CULTIVO_HIDROPONICO/Controllers/SensorController.cs
using CAPA_ENTIDADES_NEGOCIO.CLASES;
using CAPA_LOGICA_NEGOCIO.CLASES;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Security.Claims;

namespace APLICACION_CULTIVO_HIDROPONICO.Controllers
{
    [Authorize]
    public class SensorController : Controller
    {
        private UsuarioBE DatosUsuarioSesion()
        {
            var Identity = HttpContext.User.Identity as ClaimsIdentity;
            var DatosUsuarioJson = Identity.FindFirst(ClaimTypes.UserData).Value;
            return JsonConvert.DeserializeObject<UsuarioBE>(DatosUsuarioJson);
        }

        public IActionResult VerSensores()
        {
            SensorBL SensorBL = new();
            List<SensorBE> ListaSensores = SensorBL.ObtenerSensores(DatosUsuarioSesion().Id_Usuario);
            return View(ListaSensores);
        }

        public IActionResult VerSensor(int IdSensor)
        {
            SensorBL SensorBL = new();
            SensorBE SensorBE = SensorBL.ObtenerSensor(IdSensor);
            VariableBL VariableBL = new();
            List< VariableBE > Variables = VariableBL.TraerVariables();
            UnidadMedidaSensorBL UnidadMedidaSensorBL = new();
            List<UnidadMedidaSensorBE> Unidades = UnidadMedidaSensorBL.TraerUnidadesMedidaSensor();
            SensorBE_VariableBE_UnidadMedidaSensorBE SensorVarialbe = new()
            {
                Variables = Variables,
                Sensor = SensorBE,
                Unidades = Unidades,
                RolUsuarioEnSesion = DatosUsuarioSesion().Rol_Usuario
            };
            return View(SensorVarialbe);
        }

        public IActionResult CambiarNombreSensor(string NombreSensor, int IdSensor)
        {
            SensorBL SensorBL = new();
            SensorBL.CambiarNombreSensor(NombreSensor, IdSensor);
            VerSensor(IdSensor);
            return View("VerSensor");
        }

        public IActionResult CambiarRangoInferiorSensor(string RangoInferior, int IdSensor)
        {
            SensorBL SensorBL = new();
            SensorBL.CambiarRangoInferiorSensor(RangoInferior, IdSensor);
            VerSensor(IdSensor);
            return View("VerSensor");
        }

        public IActionResult CambiarRangoSuperiorSensor(string RangoSuperior, int IdSensor)
        {
            SensorBL SensorBL = new();
            SensorBL.CambiarRangoSuperiorSensor(RangoSuperior, IdSensor);
            VerSensor(IdSensor);
            return View("VerSensor");
        }

        public IActionResult CambiarVariableSensor(int VariableSensor, int IdSensor, int UnidadesSensor)
        {
            SensorBL SensorBL = new();
            SensorBL.CambiarVariableSensor(VariableSensor, IdSensor);
            SensorBL.CambiarUnidadMedidaSensor(UnidadesSensor, VariableSensor);
            VerSensor(IdSensor);
            return View("VerSensor");
        }

        public IActionResult EliminarSensor(int IdSensor)
        {
            SensorBL SensorBL = new();
            SensorBL.EliminarSensor(IdSensor);
            VerSensores();
            return View("VerSensores");
        }

        public IActionResult AgregarUnidadMedidaSensor(string UnidadMedida, string SimboloUnidad, int IdSensor)
        {
            UnidadMedidaSensorBL UnidadMedidaSensorBL = new();
            UnidadMedidaSensorBL.AgregarUnidadMedidaSensor(UnidadMedida, SimboloUnidad);
            VerSensor(IdSensor);
            return View("VerSensor");
        }
    }
}

APLICACION_CULTIVO_HIDROPONICO/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using CAPA_LOGICA_NEGOCIO.CLASES;
using CAPA_ENTIDADES_NEGOCIO.CLASES;
using Newtonsoft.Json;

namespace APLICACION_CULTIVO_HIDROPONICO.Controllers
{
    public class UsuarioController : Controller
    {

        private UsuarioBE DatosUsuarioSesion()
        {
            var Identity = HttpContext.User.Identity as ClaimsIdentity;
            var DatosUsuarioJson = Identity.FindFirst(ClaimTypes.UserData).Value;
            return JsonConvert.DeserializeObject<UsuarioBE>(DatosUsuarioJson);
        }

        public IActionResult IniciarSesion()
        {
            ClaimsPrincipal CP = HttpContext.User;
            if (CP != null)
            {
                if (CP.Identity.IsAuthenticated)
                {
                    return RedirectToAction("PaginaInicio", "Ambiente");
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Ingresar(string Correo, string Contrasena)
        {

            try
            {
                UsuarioBL UsuarioBL = new();
                UsuarioBE UsuarioBE = UsuarioBL.TraerUsuario(Correo, Contrasena);

                if (UsuarioBE != null && UsuarioBE.Estado_Usuario == "Activo")
                {
                    List<Claim> LC = new()
                    {
                        new Claim(ClaimTypes.NameIdentifier, UsuarioBE.Correo_Usuario)
                    };
                    ClaimsIdentity CI = new(LC, CookieAuthenticationDefaults.AuthenticationScheme);
                    Claim DatosUsuario = new(ClaimTypes.UserData, JsonConvert.SerializeObject(UsuarioBE));
                    CI.AddClaim(DatosUsuario);
                    AuthenticationProperties AP = new()
                    {
                        AllowRefresh = true,

                    };

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(CI), AP);
                    return RedirectToAction("PaginaInicio", "Ambiente");
                }
                else
                {
                    return View("IniciarSesion");
                }
            }
            catch (System.Exception)
            {
                return View("IniciarSesion");
            }

        }

        public IActionResult RegistrarUsuario()
        {
            return View();
        }

        public IActionResult Registrar(string NombreUsuario, string ApellidoUsuario, string TelefonoUsuario, string CorreoUsuario, string ContrasenaUsuario)
        {
            UsuarioBL UsuarioBL = new();
            UsuarioBL.RegistrarUsuario(NombreUsuario, ApellidoUsuario, TelefonoUsuario, CorreoUsuario, ContrasenaUsuario);
            return View("IniciarSesion");
        }

        [Authorize]
        public async Task<IActionResult> CerrarSesion()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View("IniciarSesion");
        }

        [Authorize]
        public IActionResult VerUsuario()
        {
            UsuarioBL UsuarioBL = new();
            UsuarioBE UsuarioBE = UsuarioBL.ObtenerUsuario(DatosUsuarioSesion().Id_Usuario);
            return View(UsuarioBE);
        }

        public IActionResult CambiarNombreUsuario(int IdUsuario, string NombreUsuario)
        {
            UsuarioBL UsuarioBL = new();
            UsuarioBL.CambiarNombreUsuario(NombreUsuario, IdUsuario);
            if (IdUsuario != DatosUsuarioSesion().Id_Usuario)
            {
                VerUsuarios();
                return View("VerUsuarios");
            }
            else
            {
                VerUsuario();
                return View("VerUsuario");
            }
        }

        public IActionResult CambiarApellidoUsuario(int IdUsuario, string ApellidoUsuario)
        {
            UsuarioBL UsuarioBL = new();
            UsuarioBL.CambiarApellidoUsuario(ApellidoUsuario, IdUsuario);
            if (IdUsuario != DatosUsuarioSesion().Id_Usuario)
            {
                VerUsuarios();
                return View("VerUsuarios");
            }
            else
            {
                VerUsuario();
                return View("VerUsuario");
            }
        }

        public IActionResult CambiarTelefonoUsuario(int IdUsuario, string TelefonoUsuario)
        {
            UsuarioBL UsuarioBL = new();
            UsuarioBL.CambiarTelefonoUsuario(TelefonoUsuario, IdUsuario);
            if (IdUsuario != DatosUsuarioSesion().Id_Usuario)
            {
                VerUsuarios();
                return View("VerUsuarios");
            }
            else
            {
                VerUsuario();
                return View("VerUsuario");
            }
        }

        public IActionResult CambiarContrasenaUsuario(string ContrasenaUsuario, string ContrasenaNuevaUsuario)
        {
            UsuarioBL UsuarioBL = new();
            UsuarioBL.CambiarContrasenaUsuario(ContrasenaUsuario, DatosUsuarioSesion().Id_Usuario, ContrasenaNuevaUsuario);
            VerUsuario();
            return View("VerUsuario");
        }

        public async Task<IActionResult> EliminarUsuario(int IdUsuario)
        {
            UsuarioBL UsuarioBL = new();
            UsuarioBL.EliminarUsuario(IdUsuario);
            await CerrarSesion();
            if (IdUsuario != DatosUsuarioSesion().Id_Usuario)
            {
                VerUsuarios();
                return View("VerUsuarios");
            }
            else
            {
                return View("IniciarSesion");
            }
        }

        public IActionResult VerUsuarios()
        {
            UsuarioBL UsuarioBL = new();
            List<UsuarioBE> Usuarios = UsuarioBL.ObtenerUsuarios();
            RolBL RolBL = new();
            List<RolBE> Roles = RolBL.TraerRoles();

            UsuarioBE_RolBE UR = new()
            {
                Usuarios = Usuarios,
                Roles = Roles
            };

            return View(UR);
        }

        public IActionResult CambiarRolUsuario(int IdUsuario, int IdRol)
        {
            UsuarioBL UsuarioBL = new();
            UsuarioBL.CambiarRolUsuario(IdUsuario, IdRol);
            VerUsuarios();
            return View("VerUsuarios");
        }

        public IActionResult GenerarReporte()
        {
            ReporteBL ReporteBL = new();
            List<ReporteBE> Reportes = ReporteBL.GenerarReporte(DatosUsuarioSesion().Id_Usuario);

            AmbienteBL AmbienteBL = new();
            List<AmbienteBE> AmbienteBE = AmbienteBL.VerAmbiente();

            ReporteBE_AmbienteBE ReporteBE_AmbienteBE = new()
            {
                Ambiente = AmbienteBE,
                Reportes = Reportes
            };

            return View(ReporteBE_AmbienteBE);
        }

    }
}

APLICACION_CULTIVO_HIDROPONICO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Righteous&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css">
    <title>@ViewData["Title"] - CULTIVO HIDROPONICO</title>
</head>
<body>
    <div class="contenedor">
        <div class="MenuLateral">
            <div class="Imagen">
                <div class="foto">
                    <img src="~/images/planti.jpg" alt="Imagen de una Planta">
                </div>
            </div>
            <div class="Enlaces">
                <div class="Elemento">
                    <a asp-controller="Ambiente" asp-action="PaginaInicio">
                        <div class="Icono IconoCultivoHidroponico">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-home" width="40"
                                 height="40" viewBox="0 0 24 24" stroke-width="2" stroke="#000000" fill="none"
                                 stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                <polyline points="5 12 3 12 12 3 21 12 19 12" />
                                <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7" />
                                <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6" />
                            </svg>
                        </div>
                        <div class="Titulo TituloCultivoHidroponico">
                            <span>Cultivo Hidropónico</span>
                        </div>
                    </a>
                </div>
                <div class="Elemento">
                    <a asp-controller="Usuario" asp-action="IniciarSesion">
                        <div class="Icono IconoIniciarSesion">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-login" width="40"
                                 height="40" viewBox="0 0 24 24" stroke-width="2" stroke="#08A71C" fill="none"
                                 stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                <path d="M14 8v-2a2 2 0 0 0 -2 -2h-7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2 -2v-2" />
                                <path d="M20 12h-13l3 -3m0 6l-3 -3" />
                            </svg>
                        </div>
                        <div class="Titulo TituloIniciarSesion">
                            <span>Iniciar Sesión</span>
                        </div>
                    </a>
                </div>
                <div class="Elemento">
                    <a asp-controller="Usuario" asp-action="VerUsuario">
                        <div class="Icono IconoVerUsuario">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user" width="40"
                                 height="40" viewBox="0 0 24 24" stroke-width="2" stroke="#88E3E7" fill="none"
                                 stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                <circle cx="12" cy="7" r="4" />
                                <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" />
                            </svg>
                        </div>
                        <div class="Titulo TituloVerUsuario">
                            <span>Mi información</span>
                        </div>
                    </a>
                </div>
                <div class="Elemento">
                    <a asp-controller="Planta" asp-action="VerPlantas">
                        <div class="Icono IconoVerPlanta">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-plant" width="40"
                                 height="40" viewBox="0 0 24 24" stroke-width="2" stroke="#2EFF00" fill="none"
                                 stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                <path d="M7 15h10v4a2 2 0 0 1 -2 2h-6a2 2 0 0 1 -2 -2v-4z" />
                                <path d="M12 9a6 6 0 0 0 -6 -6h-3v2a6 6 0 0 0 6 6h3" />
                                <path d="M12 11a6 6 0 0 1 6 -6h3v1a6 6 0 0 1 -6 6h-3" />
                                <line x1="12" y1="15" x2="12" y2="9" />
                            </svg>
                        </div>
                        <div class="Titulo TituloVerPlanta">
                            <span>Ver Plantas</span>
                        </div>
                    </a>
                </div>
                <div class="Elemento">
                    <a asp-controller="Sensor" asp-action="VerSensores">
                        <div class="Icono IconoVerSensor">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-plug" width="40"
                                 height="40" viewBox="0 0 24 24" stroke-width="2" stroke="#0013FF" fill="none"
                                 stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                <path d="M7 7h10v6a3 3 0 0 1 -3 3h-4a3 3 0 0 1 -3 -3v-6" />
                                <line x1="9" y1="3" x2="9" y2="7" />
                                <line x1="15" y1="3" x2="15" y2="7" />
                                <path d="M12 16v2a2 2 0 0 0 2 2h3" />
                            </svg>
                        </div>
                        <div class="Titulo TituloVerSensor">
                            <span>Ver Sensores</span>
                        </div>
                    </a>
                </div>
                <div class="Elemento">
                    <a asp-controller="Usuario" asp-action="CerrarSesion">
                        <div class="Icono IconoCerrarSesion">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-logout" width="40"
                                 height="40" viewBox="0 0 24 24" stroke-width="2" stroke="#FF0000" fill="none"
                                 stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                <path d="M14 8v-2a2 2 0 0 0 -2 -2h-7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2 -2v-2" />
                                <path d="M7 12h14l-3 -3m0 6l3 -3" />
                            </svg>
                        </div>
                        <div class="Titulo TituloCerrarSesion">
                            <span>Cerrar Sesión</span>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="Principal">
            @RenderBody()
        </div>
    </div>
</body>
</html>